# Generated by Django 2.2.5 on 2019-09-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(default=6, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='homecourt',
            field=models.CharField(default='Los Angeles', max_length=50),
            preserve_default=False,
        ),
    ]
