# Generated by Django 2.2.3 on 2019-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='space',
        ),
        migrations.AddField(
            model_name='park',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='long',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
            preserve_default=False,
        ),
    ]
