# Generated by Django 2.2.3 on 2019-09-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_park_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Park'),
        ),
    ]
